### PR TITLE
Fix for  Half star not working for display #12

### LINKED ISSUE #12: Half star not working for display
Hi, just tried using the stars component to display some stars and the half star is working for the selection but not display. Any help, suggestion on whats going on?

```
            <Stars
              value={4.5}
              spacing={0.8}
              half={true}
              count={5}
              starSize={20}
              backingColor="cornsilk"
              halfStar={require('../../assets/icons/star_half.png')}
              fullStar={require('../../assets/icons/star_filled.png')}
              emptyStar={require('../../assets/icons/star_empty.png')}/>
```

### PR DESCRIPTION
**Pull request by GendelfLugansk**
This should fix #12 for case when icon components are used and `opacity` is false

### CODE REVIEW

**Comment by 4umo** [comment]
Thanks for putting this together - I'm testing this branch out and it seems to be causing some issues with display mode:

**Comment by 4umo** [comment]
could you provide screenshots and the code/context required to reproduce the issue you're seeing?

**Comment by GendelfLugansk** [comment]
https://snack.expo.io/@gendelflg/react-native-stars-issue-12

**Comment by 4umo** [comment]
I was testing this branch and during testing I encountered some issues around how we're handling partial stars with custom components. I decided to sort those out independently - the latest release should resolve the issues you're facing. Thanks again for putting this together - going to close this for now.

**Pull request closed without merging**
